# Generated by Django 5.2.5 on 2025-11-20 14:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAVAapp', '0006_badge_student_correct_answers_student_current_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=500)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('bonus_xp', models.IntegerField(default=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('total_challenges_completed', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_streak', to='IAVAapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('time_spent', models.FloatField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAVAapp.dailychallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attempts', to='IAVAapp.student')),
            ],
            options={
                'ordering': ['-challenge__date'],
                'unique_together': {('student', 'challenge')},
            },
        ),
    ]
